package com.bkit.fatdown.entity;

import java.util.Date;

public class TbAdminPermissionRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_permission_role.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_permission_role.admin_id
     *
     * @mbg.generated
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_permission_role.admin_role_id
     *
     * @mbg.generated
     */
    private Integer adminRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_permission_role.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_permission_role.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin_permission_role.id
     *
     * @return the value of tb_admin_permission_role.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin_permission_role.id
     *
     * @param id the value for tb_admin_permission_role.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin_permission_role.admin_id
     *
     * @return the value of tb_admin_permission_role.admin_id
     *
     * @mbg.generated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin_permission_role.admin_id
     *
     * @param adminId the value for tb_admin_permission_role.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin_permission_role.admin_role_id
     *
     * @return the value of tb_admin_permission_role.admin_role_id
     *
     * @mbg.generated
     */
    public Integer getAdminRoleId() {
        return adminRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin_permission_role.admin_role_id
     *
     * @param adminRoleId the value for tb_admin_permission_role.admin_role_id
     *
     * @mbg.generated
     */
    public void setAdminRoleId(Integer adminRoleId) {
        this.adminRoleId = adminRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin_permission_role.gmt_create
     *
     * @return the value of tb_admin_permission_role.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin_permission_role.gmt_create
     *
     * @param gmtCreate the value for tb_admin_permission_role.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin_permission_role.gmt_modified
     *
     * @return the value of tb_admin_permission_role.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin_permission_role.gmt_modified
     *
     * @param gmtModified the value for tb_admin_permission_role.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}