package com.bkit.fatdown.entity;

import java.util.Date;

public class TbCommonQuestion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_common_question.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_common_question.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_common_question.views_total
     *
     * @mbg.generated
     */
    private Long viewsTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_common_question.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_common_question.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_common_question.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_common_question.id
     *
     * @return the value of tb_common_question.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_common_question.id
     *
     * @param id the value for tb_common_question.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_common_question.title
     *
     * @return the value of tb_common_question.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_common_question.title
     *
     * @param title the value for tb_common_question.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_common_question.views_total
     *
     * @return the value of tb_common_question.views_total
     *
     * @mbg.generated
     */
    public Long getViewsTotal() {
        return viewsTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_common_question.views_total
     *
     * @param viewsTotal the value for tb_common_question.views_total
     *
     * @mbg.generated
     */
    public void setViewsTotal(Long viewsTotal) {
        this.viewsTotal = viewsTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_common_question.status
     *
     * @return the value of tb_common_question.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_common_question.status
     *
     * @param status the value for tb_common_question.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_common_question.gmt_create
     *
     * @return the value of tb_common_question.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_common_question.gmt_create
     *
     * @param gmtCreate the value for tb_common_question.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_common_question.gmt_modified
     *
     * @return the value of tb_common_question.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_common_question.gmt_modified
     *
     * @param gmtModified the value for tb_common_question.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}