package com.bkit.fatdown.entity;

import java.util.Date;

public class TbDietMealReport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_meal_report.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_meal_report.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_meal_report.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_meal_report.real_energy
     *
     * @mbg.generated
     */
    private Double realEnergy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_meal_report.upper_energy
     *
     * @mbg.generated
     */
    private Double upperEnergy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_meal_report.lower_energy
     *
     * @mbg.generated
     */
    private Double lowerEnergy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_meal_report.energy_evaluation
     *
     * @mbg.generated
     */
    private Integer energyEvaluation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_meal_report.structure_evaluation
     *
     * @mbg.generated
     */
    private Integer structureEvaluation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_meal_report.structure_lack
     *
     * @mbg.generated
     */
    private String structureLack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_meal_report.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_meal_report.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_meal_report.id
     *
     * @return the value of tb_diet_meal_report.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_meal_report.id
     *
     * @param id the value for tb_diet_meal_report.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_meal_report.user_id
     *
     * @return the value of tb_diet_meal_report.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_meal_report.user_id
     *
     * @param userId the value for tb_diet_meal_report.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_meal_report.type
     *
     * @return the value of tb_diet_meal_report.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_meal_report.type
     *
     * @param type the value for tb_diet_meal_report.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_meal_report.real_energy
     *
     * @return the value of tb_diet_meal_report.real_energy
     *
     * @mbg.generated
     */
    public Double getRealEnergy() {
        return realEnergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_meal_report.real_energy
     *
     * @param realEnergy the value for tb_diet_meal_report.real_energy
     *
     * @mbg.generated
     */
    public void setRealEnergy(Double realEnergy) {
        this.realEnergy = realEnergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_meal_report.upper_energy
     *
     * @return the value of tb_diet_meal_report.upper_energy
     *
     * @mbg.generated
     */
    public Double getUpperEnergy() {
        return upperEnergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_meal_report.upper_energy
     *
     * @param upperEnergy the value for tb_diet_meal_report.upper_energy
     *
     * @mbg.generated
     */
    public void setUpperEnergy(Double upperEnergy) {
        this.upperEnergy = upperEnergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_meal_report.lower_energy
     *
     * @return the value of tb_diet_meal_report.lower_energy
     *
     * @mbg.generated
     */
    public Double getLowerEnergy() {
        return lowerEnergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_meal_report.lower_energy
     *
     * @param lowerEnergy the value for tb_diet_meal_report.lower_energy
     *
     * @mbg.generated
     */
    public void setLowerEnergy(Double lowerEnergy) {
        this.lowerEnergy = lowerEnergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_meal_report.energy_evaluation
     *
     * @return the value of tb_diet_meal_report.energy_evaluation
     *
     * @mbg.generated
     */
    public Integer getEnergyEvaluation() {
        return energyEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_meal_report.energy_evaluation
     *
     * @param energyEvaluation the value for tb_diet_meal_report.energy_evaluation
     *
     * @mbg.generated
     */
    public void setEnergyEvaluation(Integer energyEvaluation) {
        this.energyEvaluation = energyEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_meal_report.structure_evaluation
     *
     * @return the value of tb_diet_meal_report.structure_evaluation
     *
     * @mbg.generated
     */
    public Integer getStructureEvaluation() {
        return structureEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_meal_report.structure_evaluation
     *
     * @param structureEvaluation the value for tb_diet_meal_report.structure_evaluation
     *
     * @mbg.generated
     */
    public void setStructureEvaluation(Integer structureEvaluation) {
        this.structureEvaluation = structureEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_meal_report.structure_lack
     *
     * @return the value of tb_diet_meal_report.structure_lack
     *
     * @mbg.generated
     */
    public String getStructureLack() {
        return structureLack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_meal_report.structure_lack
     *
     * @param structureLack the value for tb_diet_meal_report.structure_lack
     *
     * @mbg.generated
     */
    public void setStructureLack(String structureLack) {
        this.structureLack = structureLack == null ? null : structureLack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_meal_report.gmt_create
     *
     * @return the value of tb_diet_meal_report.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_meal_report.gmt_create
     *
     * @param gmtCreate the value for tb_diet_meal_report.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_meal_report.gmt_modified
     *
     * @return the value of tb_diet_meal_report.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_meal_report.gmt_modified
     *
     * @param gmtModified the value for tb_diet_meal_report.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}