package com.bkit.fatdown.entity;

import java.util.Date;

public class TbDietReport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.energy
     *
     * @mbg.generated
     */
    private Double energy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.protein
     *
     * @mbg.generated
     */
    private Double protein;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.cho
     *
     * @mbg.generated
     */
    private Double cho;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.fiber
     *
     * @mbg.generated
     */
    private Double fiber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.fat
     *
     * @mbg.generated
     */
    private Double fat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.col_per
     *
     * @mbg.generated
     */
    private Double colPer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.fat_per
     *
     * @mbg.generated
     */
    private Double fatPer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.fibrin_per
     *
     * @mbg.generated
     */
    private Double fibrinPer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.protein_per
     *
     * @mbg.generated
     */
    private Double proteinPer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.structure_type_set
     *
     * @mbg.generated
     */
    private String structureTypeSet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.protein_type_set
     *
     * @mbg.generated
     */
    private String proteinTypeSet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.staple_food_type_set
     *
     * @mbg.generated
     */
    private String stapleFoodTypeSet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.fruit_vegetable_type_set
     *
     * @mbg.generated
     */
    private String fruitVegetableTypeSet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.beans_type_set
     *
     * @mbg.generated
     */
    private String beansTypeSet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.upper_energy
     *
     * @mbg.generated
     */
    private Double upperEnergy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.lower_energy
     *
     * @mbg.generated
     */
    private Double lowerEnergy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.energy_evaluation
     *
     * @mbg.generated
     */
    private Integer energyEvaluation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.structure_evaluation
     *
     * @mbg.generated
     */
    private Integer structureEvaluation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_report.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.id
     *
     * @return the value of tb_diet_report.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.id
     *
     * @param id the value for tb_diet_report.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.user_id
     *
     * @return the value of tb_diet_report.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.user_id
     *
     * @param userId the value for tb_diet_report.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.type
     *
     * @return the value of tb_diet_report.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.type
     *
     * @param type the value for tb_diet_report.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.energy
     *
     * @return the value of tb_diet_report.energy
     *
     * @mbg.generated
     */
    public Double getEnergy() {
        return energy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.energy
     *
     * @param energy the value for tb_diet_report.energy
     *
     * @mbg.generated
     */
    public void setEnergy(Double energy) {
        this.energy = energy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.protein
     *
     * @return the value of tb_diet_report.protein
     *
     * @mbg.generated
     */
    public Double getProtein() {
        return protein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.protein
     *
     * @param protein the value for tb_diet_report.protein
     *
     * @mbg.generated
     */
    public void setProtein(Double protein) {
        this.protein = protein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.cho
     *
     * @return the value of tb_diet_report.cho
     *
     * @mbg.generated
     */
    public Double getCho() {
        return cho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.cho
     *
     * @param cho the value for tb_diet_report.cho
     *
     * @mbg.generated
     */
    public void setCho(Double cho) {
        this.cho = cho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.fiber
     *
     * @return the value of tb_diet_report.fiber
     *
     * @mbg.generated
     */
    public Double getFiber() {
        return fiber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.fiber
     *
     * @param fiber the value for tb_diet_report.fiber
     *
     * @mbg.generated
     */
    public void setFiber(Double fiber) {
        this.fiber = fiber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.fat
     *
     * @return the value of tb_diet_report.fat
     *
     * @mbg.generated
     */
    public Double getFat() {
        return fat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.fat
     *
     * @param fat the value for tb_diet_report.fat
     *
     * @mbg.generated
     */
    public void setFat(Double fat) {
        this.fat = fat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.col_per
     *
     * @return the value of tb_diet_report.col_per
     *
     * @mbg.generated
     */
    public Double getColPer() {
        return colPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.col_per
     *
     * @param colPer the value for tb_diet_report.col_per
     *
     * @mbg.generated
     */
    public void setColPer(Double colPer) {
        this.colPer = colPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.fat_per
     *
     * @return the value of tb_diet_report.fat_per
     *
     * @mbg.generated
     */
    public Double getFatPer() {
        return fatPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.fat_per
     *
     * @param fatPer the value for tb_diet_report.fat_per
     *
     * @mbg.generated
     */
    public void setFatPer(Double fatPer) {
        this.fatPer = fatPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.fibrin_per
     *
     * @return the value of tb_diet_report.fibrin_per
     *
     * @mbg.generated
     */
    public Double getFibrinPer() {
        return fibrinPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.fibrin_per
     *
     * @param fibrinPer the value for tb_diet_report.fibrin_per
     *
     * @mbg.generated
     */
    public void setFibrinPer(Double fibrinPer) {
        this.fibrinPer = fibrinPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.protein_per
     *
     * @return the value of tb_diet_report.protein_per
     *
     * @mbg.generated
     */
    public Double getProteinPer() {
        return proteinPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.protein_per
     *
     * @param proteinPer the value for tb_diet_report.protein_per
     *
     * @mbg.generated
     */
    public void setProteinPer(Double proteinPer) {
        this.proteinPer = proteinPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.structure_type_set
     *
     * @return the value of tb_diet_report.structure_type_set
     *
     * @mbg.generated
     */
    public String getStructureTypeSet() {
        return structureTypeSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.structure_type_set
     *
     * @param structureTypeSet the value for tb_diet_report.structure_type_set
     *
     * @mbg.generated
     */
    public void setStructureTypeSet(String structureTypeSet) {
        this.structureTypeSet = structureTypeSet == null ? null : structureTypeSet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.protein_type_set
     *
     * @return the value of tb_diet_report.protein_type_set
     *
     * @mbg.generated
     */
    public String getProteinTypeSet() {
        return proteinTypeSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.protein_type_set
     *
     * @param proteinTypeSet the value for tb_diet_report.protein_type_set
     *
     * @mbg.generated
     */
    public void setProteinTypeSet(String proteinTypeSet) {
        this.proteinTypeSet = proteinTypeSet == null ? null : proteinTypeSet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.staple_food_type_set
     *
     * @return the value of tb_diet_report.staple_food_type_set
     *
     * @mbg.generated
     */
    public String getStapleFoodTypeSet() {
        return stapleFoodTypeSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.staple_food_type_set
     *
     * @param stapleFoodTypeSet the value for tb_diet_report.staple_food_type_set
     *
     * @mbg.generated
     */
    public void setStapleFoodTypeSet(String stapleFoodTypeSet) {
        this.stapleFoodTypeSet = stapleFoodTypeSet == null ? null : stapleFoodTypeSet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.fruit_vegetable_type_set
     *
     * @return the value of tb_diet_report.fruit_vegetable_type_set
     *
     * @mbg.generated
     */
    public String getFruitVegetableTypeSet() {
        return fruitVegetableTypeSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.fruit_vegetable_type_set
     *
     * @param fruitVegetableTypeSet the value for tb_diet_report.fruit_vegetable_type_set
     *
     * @mbg.generated
     */
    public void setFruitVegetableTypeSet(String fruitVegetableTypeSet) {
        this.fruitVegetableTypeSet = fruitVegetableTypeSet == null ? null : fruitVegetableTypeSet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.beans_type_set
     *
     * @return the value of tb_diet_report.beans_type_set
     *
     * @mbg.generated
     */
    public String getBeansTypeSet() {
        return beansTypeSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.beans_type_set
     *
     * @param beansTypeSet the value for tb_diet_report.beans_type_set
     *
     * @mbg.generated
     */
    public void setBeansTypeSet(String beansTypeSet) {
        this.beansTypeSet = beansTypeSet == null ? null : beansTypeSet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.upper_energy
     *
     * @return the value of tb_diet_report.upper_energy
     *
     * @mbg.generated
     */
    public Double getUpperEnergy() {
        return upperEnergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.upper_energy
     *
     * @param upperEnergy the value for tb_diet_report.upper_energy
     *
     * @mbg.generated
     */
    public void setUpperEnergy(Double upperEnergy) {
        this.upperEnergy = upperEnergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.lower_energy
     *
     * @return the value of tb_diet_report.lower_energy
     *
     * @mbg.generated
     */
    public Double getLowerEnergy() {
        return lowerEnergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.lower_energy
     *
     * @param lowerEnergy the value for tb_diet_report.lower_energy
     *
     * @mbg.generated
     */
    public void setLowerEnergy(Double lowerEnergy) {
        this.lowerEnergy = lowerEnergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.energy_evaluation
     *
     * @return the value of tb_diet_report.energy_evaluation
     *
     * @mbg.generated
     */
    public Integer getEnergyEvaluation() {
        return energyEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.energy_evaluation
     *
     * @param energyEvaluation the value for tb_diet_report.energy_evaluation
     *
     * @mbg.generated
     */
    public void setEnergyEvaluation(Integer energyEvaluation) {
        this.energyEvaluation = energyEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.structure_evaluation
     *
     * @return the value of tb_diet_report.structure_evaluation
     *
     * @mbg.generated
     */
    public Integer getStructureEvaluation() {
        return structureEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.structure_evaluation
     *
     * @param structureEvaluation the value for tb_diet_report.structure_evaluation
     *
     * @mbg.generated
     */
    public void setStructureEvaluation(Integer structureEvaluation) {
        this.structureEvaluation = structureEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.gmt_create
     *
     * @return the value of tb_diet_report.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.gmt_create
     *
     * @param gmtCreate the value for tb_diet_report.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_report.gmt_modified
     *
     * @return the value of tb_diet_report.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_report.gmt_modified
     *
     * @param gmtModified the value for tb_diet_report.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}