package com.bkit.fatdown.entity;

import java.util.Date;

public class TbDietUserStandard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_user_standard.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_user_standard.energy
     *
     * @mbg.generated
     */
    private Double energy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_user_standard.oil_energy
     *
     * @mbg.generated
     */
    private Double oilEnergy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_user_standard.salty_energy
     *
     * @mbg.generated
     */
    private Double saltyEnergy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_user_standard.spicy_energy
     *
     * @mbg.generated
     */
    private Double spicyEnergy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_user_standard.protein
     *
     * @mbg.generated
     */
    private Double protein;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_user_standard.fat
     *
     * @mbg.generated
     */
    private Double fat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_user_standard.carbs
     *
     * @mbg.generated
     */
    private Double carbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_user_standard.insoluble_fibre
     *
     * @mbg.generated
     */
    private Double insolubleFibre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_user_standard.cholesterol
     *
     * @mbg.generated
     */
    private Double cholesterol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_user_standard.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_user_standard.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_user_standard.id
     *
     * @return the value of tb_diet_user_standard.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_user_standard.id
     *
     * @param id the value for tb_diet_user_standard.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_user_standard.energy
     *
     * @return the value of tb_diet_user_standard.energy
     *
     * @mbg.generated
     */
    public Double getEnergy() {
        return energy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_user_standard.energy
     *
     * @param energy the value for tb_diet_user_standard.energy
     *
     * @mbg.generated
     */
    public void setEnergy(Double energy) {
        this.energy = energy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_user_standard.oil_energy
     *
     * @return the value of tb_diet_user_standard.oil_energy
     *
     * @mbg.generated
     */
    public Double getOilEnergy() {
        return oilEnergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_user_standard.oil_energy
     *
     * @param oilEnergy the value for tb_diet_user_standard.oil_energy
     *
     * @mbg.generated
     */
    public void setOilEnergy(Double oilEnergy) {
        this.oilEnergy = oilEnergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_user_standard.salty_energy
     *
     * @return the value of tb_diet_user_standard.salty_energy
     *
     * @mbg.generated
     */
    public Double getSaltyEnergy() {
        return saltyEnergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_user_standard.salty_energy
     *
     * @param saltyEnergy the value for tb_diet_user_standard.salty_energy
     *
     * @mbg.generated
     */
    public void setSaltyEnergy(Double saltyEnergy) {
        this.saltyEnergy = saltyEnergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_user_standard.spicy_energy
     *
     * @return the value of tb_diet_user_standard.spicy_energy
     *
     * @mbg.generated
     */
    public Double getSpicyEnergy() {
        return spicyEnergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_user_standard.spicy_energy
     *
     * @param spicyEnergy the value for tb_diet_user_standard.spicy_energy
     *
     * @mbg.generated
     */
    public void setSpicyEnergy(Double spicyEnergy) {
        this.spicyEnergy = spicyEnergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_user_standard.protein
     *
     * @return the value of tb_diet_user_standard.protein
     *
     * @mbg.generated
     */
    public Double getProtein() {
        return protein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_user_standard.protein
     *
     * @param protein the value for tb_diet_user_standard.protein
     *
     * @mbg.generated
     */
    public void setProtein(Double protein) {
        this.protein = protein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_user_standard.fat
     *
     * @return the value of tb_diet_user_standard.fat
     *
     * @mbg.generated
     */
    public Double getFat() {
        return fat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_user_standard.fat
     *
     * @param fat the value for tb_diet_user_standard.fat
     *
     * @mbg.generated
     */
    public void setFat(Double fat) {
        this.fat = fat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_user_standard.carbs
     *
     * @return the value of tb_diet_user_standard.carbs
     *
     * @mbg.generated
     */
    public Double getCarbs() {
        return carbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_user_standard.carbs
     *
     * @param carbs the value for tb_diet_user_standard.carbs
     *
     * @mbg.generated
     */
    public void setCarbs(Double carbs) {
        this.carbs = carbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_user_standard.insoluble_fibre
     *
     * @return the value of tb_diet_user_standard.insoluble_fibre
     *
     * @mbg.generated
     */
    public Double getInsolubleFibre() {
        return insolubleFibre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_user_standard.insoluble_fibre
     *
     * @param insolubleFibre the value for tb_diet_user_standard.insoluble_fibre
     *
     * @mbg.generated
     */
    public void setInsolubleFibre(Double insolubleFibre) {
        this.insolubleFibre = insolubleFibre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_user_standard.cholesterol
     *
     * @return the value of tb_diet_user_standard.cholesterol
     *
     * @mbg.generated
     */
    public Double getCholesterol() {
        return cholesterol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_user_standard.cholesterol
     *
     * @param cholesterol the value for tb_diet_user_standard.cholesterol
     *
     * @mbg.generated
     */
    public void setCholesterol(Double cholesterol) {
        this.cholesterol = cholesterol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_user_standard.gmt_create
     *
     * @return the value of tb_diet_user_standard.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_user_standard.gmt_create
     *
     * @param gmtCreate the value for tb_diet_user_standard.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_user_standard.gmt_modified
     *
     * @return the value of tb_diet_user_standard.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_user_standard.gmt_modified
     *
     * @param gmtModified the value for tb_diet_user_standard.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}