package com.bkit.fatdown.entity;

import java.util.Date;

public class TbDietRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_record.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_record.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_record.energy
     *
     * @mbg.generated
     */
    private Double energy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_record.protein
     *
     * @mbg.generated
     */
    private Double protein;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_record.cho
     *
     * @mbg.generated
     */
    private Double cho;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_record.fiber
     *
     * @mbg.generated
     */
    private Double fiber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_record.fat
     *
     * @mbg.generated
     */
    private Double fat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_record.good_protein
     *
     * @mbg.generated
     */
    private Double goodProtein;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_record.animal_fat
     *
     * @mbg.generated
     */
    private Double animalFat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_record.structure_set
     *
     * @mbg.generated
     */
    private String structureSet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_record.protein_set
     *
     * @mbg.generated
     */
    private String proteinSet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_record.staple_food_set
     *
     * @mbg.generated
     */
    private String stapleFoodSet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_record.fruit_vegetable_set
     *
     * @mbg.generated
     */
    private String fruitVegetableSet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_record.beans_set
     *
     * @mbg.generated
     */
    private String beansSet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_record.nuts_set
     *
     * @mbg.generated
     */
    private String nutsSet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_record.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_diet_record.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_record.id
     *
     * @return the value of tb_diet_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_record.id
     *
     * @param id the value for tb_diet_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_record.user_id
     *
     * @return the value of tb_diet_record.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_record.user_id
     *
     * @param userId the value for tb_diet_record.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_record.type
     *
     * @return the value of tb_diet_record.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_record.type
     *
     * @param type the value for tb_diet_record.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_record.energy
     *
     * @return the value of tb_diet_record.energy
     *
     * @mbg.generated
     */
    public Double getEnergy() {
        return energy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_record.energy
     *
     * @param energy the value for tb_diet_record.energy
     *
     * @mbg.generated
     */
    public void setEnergy(Double energy) {
        this.energy = energy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_record.protein
     *
     * @return the value of tb_diet_record.protein
     *
     * @mbg.generated
     */
    public Double getProtein() {
        return protein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_record.protein
     *
     * @param protein the value for tb_diet_record.protein
     *
     * @mbg.generated
     */
    public void setProtein(Double protein) {
        this.protein = protein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_record.cho
     *
     * @return the value of tb_diet_record.cho
     *
     * @mbg.generated
     */
    public Double getCho() {
        return cho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_record.cho
     *
     * @param cho the value for tb_diet_record.cho
     *
     * @mbg.generated
     */
    public void setCho(Double cho) {
        this.cho = cho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_record.fiber
     *
     * @return the value of tb_diet_record.fiber
     *
     * @mbg.generated
     */
    public Double getFiber() {
        return fiber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_record.fiber
     *
     * @param fiber the value for tb_diet_record.fiber
     *
     * @mbg.generated
     */
    public void setFiber(Double fiber) {
        this.fiber = fiber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_record.fat
     *
     * @return the value of tb_diet_record.fat
     *
     * @mbg.generated
     */
    public Double getFat() {
        return fat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_record.fat
     *
     * @param fat the value for tb_diet_record.fat
     *
     * @mbg.generated
     */
    public void setFat(Double fat) {
        this.fat = fat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_record.good_protein
     *
     * @return the value of tb_diet_record.good_protein
     *
     * @mbg.generated
     */
    public Double getGoodProtein() {
        return goodProtein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_record.good_protein
     *
     * @param goodProtein the value for tb_diet_record.good_protein
     *
     * @mbg.generated
     */
    public void setGoodProtein(Double goodProtein) {
        this.goodProtein = goodProtein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_record.animal_fat
     *
     * @return the value of tb_diet_record.animal_fat
     *
     * @mbg.generated
     */
    public Double getAnimalFat() {
        return animalFat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_record.animal_fat
     *
     * @param animalFat the value for tb_diet_record.animal_fat
     *
     * @mbg.generated
     */
    public void setAnimalFat(Double animalFat) {
        this.animalFat = animalFat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_record.structure_set
     *
     * @return the value of tb_diet_record.structure_set
     *
     * @mbg.generated
     */
    public String getStructureSet() {
        return structureSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_record.structure_set
     *
     * @param structureSet the value for tb_diet_record.structure_set
     *
     * @mbg.generated
     */
    public void setStructureSet(String structureSet) {
        this.structureSet = structureSet == null ? null : structureSet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_record.protein_set
     *
     * @return the value of tb_diet_record.protein_set
     *
     * @mbg.generated
     */
    public String getProteinSet() {
        return proteinSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_record.protein_set
     *
     * @param proteinSet the value for tb_diet_record.protein_set
     *
     * @mbg.generated
     */
    public void setProteinSet(String proteinSet) {
        this.proteinSet = proteinSet == null ? null : proteinSet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_record.staple_food_set
     *
     * @return the value of tb_diet_record.staple_food_set
     *
     * @mbg.generated
     */
    public String getStapleFoodSet() {
        return stapleFoodSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_record.staple_food_set
     *
     * @param stapleFoodSet the value for tb_diet_record.staple_food_set
     *
     * @mbg.generated
     */
    public void setStapleFoodSet(String stapleFoodSet) {
        this.stapleFoodSet = stapleFoodSet == null ? null : stapleFoodSet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_record.fruit_vegetable_set
     *
     * @return the value of tb_diet_record.fruit_vegetable_set
     *
     * @mbg.generated
     */
    public String getFruitVegetableSet() {
        return fruitVegetableSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_record.fruit_vegetable_set
     *
     * @param fruitVegetableSet the value for tb_diet_record.fruit_vegetable_set
     *
     * @mbg.generated
     */
    public void setFruitVegetableSet(String fruitVegetableSet) {
        this.fruitVegetableSet = fruitVegetableSet == null ? null : fruitVegetableSet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_record.beans_set
     *
     * @return the value of tb_diet_record.beans_set
     *
     * @mbg.generated
     */
    public String getBeansSet() {
        return beansSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_record.beans_set
     *
     * @param beansSet the value for tb_diet_record.beans_set
     *
     * @mbg.generated
     */
    public void setBeansSet(String beansSet) {
        this.beansSet = beansSet == null ? null : beansSet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_record.nuts_set
     *
     * @return the value of tb_diet_record.nuts_set
     *
     * @mbg.generated
     */
    public String getNutsSet() {
        return nutsSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_record.nuts_set
     *
     * @param nutsSet the value for tb_diet_record.nuts_set
     *
     * @mbg.generated
     */
    public void setNutsSet(String nutsSet) {
        this.nutsSet = nutsSet == null ? null : nutsSet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_record.gmt_create
     *
     * @return the value of tb_diet_record.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_record.gmt_create
     *
     * @param gmtCreate the value for tb_diet_record.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diet_record.gmt_modified
     *
     * @return the value of tb_diet_record.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diet_record.gmt_modified
     *
     * @param gmtModified the value for tb_diet_record.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}