package com.bkit.fatdown.entity;

import java.util.Date;

public class TbElementBasic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.goodProtein
     *
     * @mbg.generated
     */
    private Integer goodprotein;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.animalFat
     *
     * @mbg.generated
     */
    private Integer animalfat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.edible
     *
     * @mbg.generated
     */
    private Double edible;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.water
     *
     * @mbg.generated
     */
    private Double water;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.energy
     *
     * @mbg.generated
     */
    private Double energy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.protein
     *
     * @mbg.generated
     */
    private Double protein;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.fat
     *
     * @mbg.generated
     */
    private Double fat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.cho
     *
     * @mbg.generated
     */
    private Double cho;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.fiber
     *
     * @mbg.generated
     */
    private Double fiber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.cholesterol
     *
     * @mbg.generated
     */
    private Double cholesterol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.ash
     *
     * @mbg.generated
     */
    private Double ash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.vitamin_A
     *
     * @mbg.generated
     */
    private Double vitaminA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.carotene
     *
     * @mbg.generated
     */
    private Double carotene;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.retinol
     *
     * @mbg.generated
     */
    private Double retinol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.thiamin
     *
     * @mbg.generated
     */
    private Double thiamin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.riboflavin
     *
     * @mbg.generated
     */
    private Double riboflavin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.niacin
     *
     * @mbg.generated
     */
    private Double niacin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.vitamin_C
     *
     * @mbg.generated
     */
    private Double vitaminC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.vitamin_E
     *
     * @mbg.generated
     */
    private Double vitaminE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.ca
     *
     * @mbg.generated
     */
    private Double ca;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.p
     *
     * @mbg.generated
     */
    private Double p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.k
     *
     * @mbg.generated
     */
    private Double k;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.na
     *
     * @mbg.generated
     */
    private Double na;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.mg
     *
     * @mbg.generated
     */
    private Double mg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.fe
     *
     * @mbg.generated
     */
    private Double fe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.zn
     *
     * @mbg.generated
     */
    private Double zn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.se
     *
     * @mbg.generated
     */
    private Double se;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.cu
     *
     * @mbg.generated
     */
    private Double cu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.mn
     *
     * @mbg.generated
     */
    private Double mn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_element_basic.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.id
     *
     * @return the value of tb_element_basic.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.id
     *
     * @param id the value for tb_element_basic.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.name
     *
     * @return the value of tb_element_basic.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.name
     *
     * @param name the value for tb_element_basic.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.type
     *
     * @return the value of tb_element_basic.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.type
     *
     * @param type the value for tb_element_basic.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.goodProtein
     *
     * @return the value of tb_element_basic.goodProtein
     *
     * @mbg.generated
     */
    public Integer getGoodprotein() {
        return goodprotein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.goodProtein
     *
     * @param goodprotein the value for tb_element_basic.goodProtein
     *
     * @mbg.generated
     */
    public void setGoodprotein(Integer goodprotein) {
        this.goodprotein = goodprotein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.animalFat
     *
     * @return the value of tb_element_basic.animalFat
     *
     * @mbg.generated
     */
    public Integer getAnimalfat() {
        return animalfat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.animalFat
     *
     * @param animalfat the value for tb_element_basic.animalFat
     *
     * @mbg.generated
     */
    public void setAnimalfat(Integer animalfat) {
        this.animalfat = animalfat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.edible
     *
     * @return the value of tb_element_basic.edible
     *
     * @mbg.generated
     */
    public Double getEdible() {
        return edible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.edible
     *
     * @param edible the value for tb_element_basic.edible
     *
     * @mbg.generated
     */
    public void setEdible(Double edible) {
        this.edible = edible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.water
     *
     * @return the value of tb_element_basic.water
     *
     * @mbg.generated
     */
    public Double getWater() {
        return water;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.water
     *
     * @param water the value for tb_element_basic.water
     *
     * @mbg.generated
     */
    public void setWater(Double water) {
        this.water = water;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.energy
     *
     * @return the value of tb_element_basic.energy
     *
     * @mbg.generated
     */
    public Double getEnergy() {
        return energy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.energy
     *
     * @param energy the value for tb_element_basic.energy
     *
     * @mbg.generated
     */
    public void setEnergy(Double energy) {
        this.energy = energy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.protein
     *
     * @return the value of tb_element_basic.protein
     *
     * @mbg.generated
     */
    public Double getProtein() {
        return protein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.protein
     *
     * @param protein the value for tb_element_basic.protein
     *
     * @mbg.generated
     */
    public void setProtein(Double protein) {
        this.protein = protein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.fat
     *
     * @return the value of tb_element_basic.fat
     *
     * @mbg.generated
     */
    public Double getFat() {
        return fat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.fat
     *
     * @param fat the value for tb_element_basic.fat
     *
     * @mbg.generated
     */
    public void setFat(Double fat) {
        this.fat = fat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.cho
     *
     * @return the value of tb_element_basic.cho
     *
     * @mbg.generated
     */
    public Double getCho() {
        return cho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.cho
     *
     * @param cho the value for tb_element_basic.cho
     *
     * @mbg.generated
     */
    public void setCho(Double cho) {
        this.cho = cho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.fiber
     *
     * @return the value of tb_element_basic.fiber
     *
     * @mbg.generated
     */
    public Double getFiber() {
        return fiber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.fiber
     *
     * @param fiber the value for tb_element_basic.fiber
     *
     * @mbg.generated
     */
    public void setFiber(Double fiber) {
        this.fiber = fiber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.cholesterol
     *
     * @return the value of tb_element_basic.cholesterol
     *
     * @mbg.generated
     */
    public Double getCholesterol() {
        return cholesterol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.cholesterol
     *
     * @param cholesterol the value for tb_element_basic.cholesterol
     *
     * @mbg.generated
     */
    public void setCholesterol(Double cholesterol) {
        this.cholesterol = cholesterol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.ash
     *
     * @return the value of tb_element_basic.ash
     *
     * @mbg.generated
     */
    public Double getAsh() {
        return ash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.ash
     *
     * @param ash the value for tb_element_basic.ash
     *
     * @mbg.generated
     */
    public void setAsh(Double ash) {
        this.ash = ash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.vitamin_A
     *
     * @return the value of tb_element_basic.vitamin_A
     *
     * @mbg.generated
     */
    public Double getVitaminA() {
        return vitaminA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.vitamin_A
     *
     * @param vitaminA the value for tb_element_basic.vitamin_A
     *
     * @mbg.generated
     */
    public void setVitaminA(Double vitaminA) {
        this.vitaminA = vitaminA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.carotene
     *
     * @return the value of tb_element_basic.carotene
     *
     * @mbg.generated
     */
    public Double getCarotene() {
        return carotene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.carotene
     *
     * @param carotene the value for tb_element_basic.carotene
     *
     * @mbg.generated
     */
    public void setCarotene(Double carotene) {
        this.carotene = carotene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.retinol
     *
     * @return the value of tb_element_basic.retinol
     *
     * @mbg.generated
     */
    public Double getRetinol() {
        return retinol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.retinol
     *
     * @param retinol the value for tb_element_basic.retinol
     *
     * @mbg.generated
     */
    public void setRetinol(Double retinol) {
        this.retinol = retinol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.thiamin
     *
     * @return the value of tb_element_basic.thiamin
     *
     * @mbg.generated
     */
    public Double getThiamin() {
        return thiamin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.thiamin
     *
     * @param thiamin the value for tb_element_basic.thiamin
     *
     * @mbg.generated
     */
    public void setThiamin(Double thiamin) {
        this.thiamin = thiamin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.riboflavin
     *
     * @return the value of tb_element_basic.riboflavin
     *
     * @mbg.generated
     */
    public Double getRiboflavin() {
        return riboflavin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.riboflavin
     *
     * @param riboflavin the value for tb_element_basic.riboflavin
     *
     * @mbg.generated
     */
    public void setRiboflavin(Double riboflavin) {
        this.riboflavin = riboflavin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.niacin
     *
     * @return the value of tb_element_basic.niacin
     *
     * @mbg.generated
     */
    public Double getNiacin() {
        return niacin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.niacin
     *
     * @param niacin the value for tb_element_basic.niacin
     *
     * @mbg.generated
     */
    public void setNiacin(Double niacin) {
        this.niacin = niacin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.vitamin_C
     *
     * @return the value of tb_element_basic.vitamin_C
     *
     * @mbg.generated
     */
    public Double getVitaminC() {
        return vitaminC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.vitamin_C
     *
     * @param vitaminC the value for tb_element_basic.vitamin_C
     *
     * @mbg.generated
     */
    public void setVitaminC(Double vitaminC) {
        this.vitaminC = vitaminC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.vitamin_E
     *
     * @return the value of tb_element_basic.vitamin_E
     *
     * @mbg.generated
     */
    public Double getVitaminE() {
        return vitaminE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.vitamin_E
     *
     * @param vitaminE the value for tb_element_basic.vitamin_E
     *
     * @mbg.generated
     */
    public void setVitaminE(Double vitaminE) {
        this.vitaminE = vitaminE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.ca
     *
     * @return the value of tb_element_basic.ca
     *
     * @mbg.generated
     */
    public Double getCa() {
        return ca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.ca
     *
     * @param ca the value for tb_element_basic.ca
     *
     * @mbg.generated
     */
    public void setCa(Double ca) {
        this.ca = ca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.p
     *
     * @return the value of tb_element_basic.p
     *
     * @mbg.generated
     */
    public Double getP() {
        return p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.p
     *
     * @param p the value for tb_element_basic.p
     *
     * @mbg.generated
     */
    public void setP(Double p) {
        this.p = p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.k
     *
     * @return the value of tb_element_basic.k
     *
     * @mbg.generated
     */
    public Double getK() {
        return k;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.k
     *
     * @param k the value for tb_element_basic.k
     *
     * @mbg.generated
     */
    public void setK(Double k) {
        this.k = k;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.na
     *
     * @return the value of tb_element_basic.na
     *
     * @mbg.generated
     */
    public Double getNa() {
        return na;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.na
     *
     * @param na the value for tb_element_basic.na
     *
     * @mbg.generated
     */
    public void setNa(Double na) {
        this.na = na;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.mg
     *
     * @return the value of tb_element_basic.mg
     *
     * @mbg.generated
     */
    public Double getMg() {
        return mg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.mg
     *
     * @param mg the value for tb_element_basic.mg
     *
     * @mbg.generated
     */
    public void setMg(Double mg) {
        this.mg = mg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.fe
     *
     * @return the value of tb_element_basic.fe
     *
     * @mbg.generated
     */
    public Double getFe() {
        return fe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.fe
     *
     * @param fe the value for tb_element_basic.fe
     *
     * @mbg.generated
     */
    public void setFe(Double fe) {
        this.fe = fe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.zn
     *
     * @return the value of tb_element_basic.zn
     *
     * @mbg.generated
     */
    public Double getZn() {
        return zn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.zn
     *
     * @param zn the value for tb_element_basic.zn
     *
     * @mbg.generated
     */
    public void setZn(Double zn) {
        this.zn = zn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.se
     *
     * @return the value of tb_element_basic.se
     *
     * @mbg.generated
     */
    public Double getSe() {
        return se;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.se
     *
     * @param se the value for tb_element_basic.se
     *
     * @mbg.generated
     */
    public void setSe(Double se) {
        this.se = se;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.cu
     *
     * @return the value of tb_element_basic.cu
     *
     * @mbg.generated
     */
    public Double getCu() {
        return cu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.cu
     *
     * @param cu the value for tb_element_basic.cu
     *
     * @mbg.generated
     */
    public void setCu(Double cu) {
        this.cu = cu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.mn
     *
     * @return the value of tb_element_basic.mn
     *
     * @mbg.generated
     */
    public Double getMn() {
        return mn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.mn
     *
     * @param mn the value for tb_element_basic.mn
     *
     * @mbg.generated
     */
    public void setMn(Double mn) {
        this.mn = mn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.gmt_create
     *
     * @return the value of tb_element_basic.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.gmt_create
     *
     * @param gmtCreate the value for tb_element_basic.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_element_basic.gmt_modified
     *
     * @return the value of tb_element_basic.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_element_basic.gmt_modified
     *
     * @param gmtModified the value for tb_element_basic.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}