package com.bkit.fatdown.entity;

import java.util.Date;

public class TbFeedbackInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_feedback_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_feedback_info.type_id
     *
     * @mbg.generated
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_feedback_info.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_feedback_info.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_feedback_info.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_feedback_info.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_feedback_info.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_feedback_info.img_url_set
     *
     * @mbg.generated
     */
    private String imgUrlSet;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_feedback_info.id
     *
     * @return the value of tb_feedback_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_feedback_info.id
     *
     * @param id the value for tb_feedback_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_feedback_info.type_id
     *
     * @return the value of tb_feedback_info.type_id
     *
     * @mbg.generated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_feedback_info.type_id
     *
     * @param typeId the value for tb_feedback_info.type_id
     *
     * @mbg.generated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_feedback_info.user_id
     *
     * @return the value of tb_feedback_info.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_feedback_info.user_id
     *
     * @param userId the value for tb_feedback_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_feedback_info.content
     *
     * @return the value of tb_feedback_info.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_feedback_info.content
     *
     * @param content the value for tb_feedback_info.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_feedback_info.status
     *
     * @return the value of tb_feedback_info.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_feedback_info.status
     *
     * @param status the value for tb_feedback_info.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_feedback_info.gmt_create
     *
     * @return the value of tb_feedback_info.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_feedback_info.gmt_create
     *
     * @param gmtCreate the value for tb_feedback_info.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_feedback_info.gmt_modified
     *
     * @return the value of tb_feedback_info.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_feedback_info.gmt_modified
     *
     * @param gmtModified the value for tb_feedback_info.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_feedback_info.img_url_set
     *
     * @return the value of tb_feedback_info.img_url_set
     *
     * @mbg.generated
     */
    public String getImgUrlSet() {
        return imgUrlSet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_feedback_info.img_url_set
     *
     * @param imgUrlSet the value for tb_feedback_info.img_url_set
     *
     * @mbg.generated
     */
    public void setImgUrlSet(String imgUrlSet) {
        this.imgUrlSet = imgUrlSet == null ? null : imgUrlSet.trim();
    }
}