package com.bkit.fatdown.entity;

import java.util.Date;

public class TbFoodRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_food_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_food_record.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_food_record.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_food_record.food_id
     *
     * @mbg.generated
     */
    private Integer foodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_food_record.eat_per
     *
     * @mbg.generated
     */
    private Double eatPer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_food_record.food_quantity
     *
     * @mbg.generated
     */
    private Double foodQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_food_record.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_food_record.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_food_record.id
     *
     * @return the value of tb_food_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_food_record.id
     *
     * @param id the value for tb_food_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_food_record.img_url
     *
     * @return the value of tb_food_record.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_food_record.img_url
     *
     * @param imgUrl the value for tb_food_record.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_food_record.user_id
     *
     * @return the value of tb_food_record.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_food_record.user_id
     *
     * @param userId the value for tb_food_record.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_food_record.food_id
     *
     * @return the value of tb_food_record.food_id
     *
     * @mbg.generated
     */
    public Integer getFoodId() {
        return foodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_food_record.food_id
     *
     * @param foodId the value for tb_food_record.food_id
     *
     * @mbg.generated
     */
    public void setFoodId(Integer foodId) {
        this.foodId = foodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_food_record.eat_per
     *
     * @return the value of tb_food_record.eat_per
     *
     * @mbg.generated
     */
    public Double getEatPer() {
        return eatPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_food_record.eat_per
     *
     * @param eatPer the value for tb_food_record.eat_per
     *
     * @mbg.generated
     */
    public void setEatPer(Double eatPer) {
        this.eatPer = eatPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_food_record.food_quantity
     *
     * @return the value of tb_food_record.food_quantity
     *
     * @mbg.generated
     */
    public Double getFoodQuantity() {
        return foodQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_food_record.food_quantity
     *
     * @param foodQuantity the value for tb_food_record.food_quantity
     *
     * @mbg.generated
     */
    public void setFoodQuantity(Double foodQuantity) {
        this.foodQuantity = foodQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_food_record.gmt_create
     *
     * @return the value of tb_food_record.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_food_record.gmt_create
     *
     * @param gmtCreate the value for tb_food_record.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_food_record.gmt_modified
     *
     * @return the value of tb_food_record.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_food_record.gmt_modified
     *
     * @param gmtModified the value for tb_food_record.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}