package com.bkit.fatdown.entity;

import java.util.Date;

public class TbFoodRecommend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_food_recommend.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_food_recommend.food_name
     *
     * @mbg.generated
     */
    private String foodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_food_recommend.food_type
     *
     * @mbg.generated
     */
    private Integer foodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_food_recommend.total
     *
     * @mbg.generated
     */
    private Integer total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_food_recommend.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_food_recommend.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_food_recommend.id
     *
     * @return the value of tb_food_recommend.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_food_recommend.id
     *
     * @param id the value for tb_food_recommend.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_food_recommend.food_name
     *
     * @return the value of tb_food_recommend.food_name
     *
     * @mbg.generated
     */
    public String getFoodName() {
        return foodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_food_recommend.food_name
     *
     * @param foodName the value for tb_food_recommend.food_name
     *
     * @mbg.generated
     */
    public void setFoodName(String foodName) {
        this.foodName = foodName == null ? null : foodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_food_recommend.food_type
     *
     * @return the value of tb_food_recommend.food_type
     *
     * @mbg.generated
     */
    public Integer getFoodType() {
        return foodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_food_recommend.food_type
     *
     * @param foodType the value for tb_food_recommend.food_type
     *
     * @mbg.generated
     */
    public void setFoodType(Integer foodType) {
        this.foodType = foodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_food_recommend.total
     *
     * @return the value of tb_food_recommend.total
     *
     * @mbg.generated
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_food_recommend.total
     *
     * @param total the value for tb_food_recommend.total
     *
     * @mbg.generated
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_food_recommend.gmt_create
     *
     * @return the value of tb_food_recommend.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_food_recommend.gmt_create
     *
     * @param gmtCreate the value for tb_food_recommend.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_food_recommend.gmt_modified
     *
     * @return the value of tb_food_recommend.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_food_recommend.gmt_modified
     *
     * @param gmtModified the value for tb_food_recommend.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}