package com.bkit.fatdown.entity;

import java.util.Date;

public class TbScoreRecordKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score_record.user
     *
     * @mbg.generated
     */
    private Integer user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score_record.start
     *
     * @mbg.generated
     */
    private Date start;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score_record.end
     *
     * @mbg.generated
     */
    private Date end;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_record.user
     *
     * @return the value of tb_score_record.user
     *
     * @mbg.generated
     */
    public Integer getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_record.user
     *
     * @param user the value for tb_score_record.user
     *
     * @mbg.generated
     */
    public void setUser(Integer user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_record.start
     *
     * @return the value of tb_score_record.start
     *
     * @mbg.generated
     */
    public Date getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_record.start
     *
     * @param start the value for tb_score_record.start
     *
     * @mbg.generated
     */
    public void setStart(Date start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score_record.end
     *
     * @return the value of tb_score_record.end
     *
     * @mbg.generated
     */
    public Date getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score_record.end
     *
     * @param end the value for tb_score_record.end
     *
     * @mbg.generated
     */
    public void setEnd(Date end) {
        this.end = end;
    }
}