package com.bkit.fatdown.entity;

import java.util.Date;

public class TbTestRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test_record.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test_record.question_id
     *
     * @mbg.generated
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test_record.paper_id
     *
     * @mbg.generated
     */
    private Integer paperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test_record.user_answer
     *
     * @mbg.generated
     */
    private String userAnswer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test_record.user_score
     *
     * @mbg.generated
     */
    private Double userScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test_record.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test_record.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test_record.id
     *
     * @return the value of tb_test_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test_record.id
     *
     * @param id the value for tb_test_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test_record.user_id
     *
     * @return the value of tb_test_record.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test_record.user_id
     *
     * @param userId the value for tb_test_record.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test_record.question_id
     *
     * @return the value of tb_test_record.question_id
     *
     * @mbg.generated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test_record.question_id
     *
     * @param questionId the value for tb_test_record.question_id
     *
     * @mbg.generated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test_record.paper_id
     *
     * @return the value of tb_test_record.paper_id
     *
     * @mbg.generated
     */
    public Integer getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test_record.paper_id
     *
     * @param paperId the value for tb_test_record.paper_id
     *
     * @mbg.generated
     */
    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test_record.user_answer
     *
     * @return the value of tb_test_record.user_answer
     *
     * @mbg.generated
     */
    public String getUserAnswer() {
        return userAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test_record.user_answer
     *
     * @param userAnswer the value for tb_test_record.user_answer
     *
     * @mbg.generated
     */
    public void setUserAnswer(String userAnswer) {
        this.userAnswer = userAnswer == null ? null : userAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test_record.user_score
     *
     * @return the value of tb_test_record.user_score
     *
     * @mbg.generated
     */
    public Double getUserScore() {
        return userScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test_record.user_score
     *
     * @param userScore the value for tb_test_record.user_score
     *
     * @mbg.generated
     */
    public void setUserScore(Double userScore) {
        this.userScore = userScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test_record.gmt_create
     *
     * @return the value of tb_test_record.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test_record.gmt_create
     *
     * @param gmtCreate the value for tb_test_record.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test_record.gmt_modified
     *
     * @return the value of tb_test_record.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test_record.gmt_modified
     *
     * @param gmtModified the value for tb_test_record.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}