package com.bkit.fatdown.entity;

public class TbTestRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test_record.question_id
     *
     * @mbg.generated
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test_record.paper_id
     *
     * @mbg.generated
     */
    private Integer paperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test_record.answer
     *
     * @mbg.generated
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test_record.user
     *
     * @mbg.generated
     */
    private Integer user;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test_record.id
     *
     * @return the value of tb_test_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test_record.id
     *
     * @param id the value for tb_test_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test_record.question_id
     *
     * @return the value of tb_test_record.question_id
     *
     * @mbg.generated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test_record.question_id
     *
     * @param questionId the value for tb_test_record.question_id
     *
     * @mbg.generated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test_record.paper_id
     *
     * @return the value of tb_test_record.paper_id
     *
     * @mbg.generated
     */
    public Integer getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test_record.paper_id
     *
     * @param paperId the value for tb_test_record.paper_id
     *
     * @mbg.generated
     */
    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test_record.answer
     *
     * @return the value of tb_test_record.answer
     *
     * @mbg.generated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test_record.answer
     *
     * @param answer the value for tb_test_record.answer
     *
     * @mbg.generated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test_record.user
     *
     * @return the value of tb_test_record.user
     *
     * @mbg.generated
     */
    public Integer getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test_record.user
     *
     * @param user the value for tb_test_record.user
     *
     * @mbg.generated
     */
    public void setUser(Integer user) {
        this.user = user;
    }
}