package com.bkit.fatdown.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbUserPrivacyInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user_privacy_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user_privacy_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user_privacy_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_privacy_info
     *
     * @mbg.generated
     */
    public TbUserPrivacyInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_privacy_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_privacy_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_privacy_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_privacy_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_privacy_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_privacy_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_privacy_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_privacy_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_privacy_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_privacy_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_user_privacy_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createDate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("createDate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("createDate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("createDate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("createDate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("createDate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("createDate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("createDate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("createDate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("createDate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("createDate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andFatrateIsNull() {
            addCriterion("fatRate is null");
            return (Criteria) this;
        }

        public Criteria andFatrateIsNotNull() {
            addCriterion("fatRate is not null");
            return (Criteria) this;
        }

        public Criteria andFatrateEqualTo(Double value) {
            addCriterion("fatRate =", value, "fatrate");
            return (Criteria) this;
        }

        public Criteria andFatrateNotEqualTo(Double value) {
            addCriterion("fatRate <>", value, "fatrate");
            return (Criteria) this;
        }

        public Criteria andFatrateGreaterThan(Double value) {
            addCriterion("fatRate >", value, "fatrate");
            return (Criteria) this;
        }

        public Criteria andFatrateGreaterThanOrEqualTo(Double value) {
            addCriterion("fatRate >=", value, "fatrate");
            return (Criteria) this;
        }

        public Criteria andFatrateLessThan(Double value) {
            addCriterion("fatRate <", value, "fatrate");
            return (Criteria) this;
        }

        public Criteria andFatrateLessThanOrEqualTo(Double value) {
            addCriterion("fatRate <=", value, "fatrate");
            return (Criteria) this;
        }

        public Criteria andFatrateIn(List<Double> values) {
            addCriterion("fatRate in", values, "fatrate");
            return (Criteria) this;
        }

        public Criteria andFatrateNotIn(List<Double> values) {
            addCriterion("fatRate not in", values, "fatrate");
            return (Criteria) this;
        }

        public Criteria andFatrateBetween(Double value1, Double value2) {
            addCriterion("fatRate between", value1, value2, "fatrate");
            return (Criteria) this;
        }

        public Criteria andFatrateNotBetween(Double value1, Double value2) {
            addCriterion("fatRate not between", value1, value2, "fatrate");
            return (Criteria) this;
        }

        public Criteria andBustIsNull() {
            addCriterion("bust is null");
            return (Criteria) this;
        }

        public Criteria andBustIsNotNull() {
            addCriterion("bust is not null");
            return (Criteria) this;
        }

        public Criteria andBustEqualTo(Double value) {
            addCriterion("bust =", value, "bust");
            return (Criteria) this;
        }

        public Criteria andBustNotEqualTo(Double value) {
            addCriterion("bust <>", value, "bust");
            return (Criteria) this;
        }

        public Criteria andBustGreaterThan(Double value) {
            addCriterion("bust >", value, "bust");
            return (Criteria) this;
        }

        public Criteria andBustGreaterThanOrEqualTo(Double value) {
            addCriterion("bust >=", value, "bust");
            return (Criteria) this;
        }

        public Criteria andBustLessThan(Double value) {
            addCriterion("bust <", value, "bust");
            return (Criteria) this;
        }

        public Criteria andBustLessThanOrEqualTo(Double value) {
            addCriterion("bust <=", value, "bust");
            return (Criteria) this;
        }

        public Criteria andBustIn(List<Double> values) {
            addCriterion("bust in", values, "bust");
            return (Criteria) this;
        }

        public Criteria andBustNotIn(List<Double> values) {
            addCriterion("bust not in", values, "bust");
            return (Criteria) this;
        }

        public Criteria andBustBetween(Double value1, Double value2) {
            addCriterion("bust between", value1, value2, "bust");
            return (Criteria) this;
        }

        public Criteria andBustNotBetween(Double value1, Double value2) {
            addCriterion("bust not between", value1, value2, "bust");
            return (Criteria) this;
        }

        public Criteria andWaistIsNull() {
            addCriterion("waist is null");
            return (Criteria) this;
        }

        public Criteria andWaistIsNotNull() {
            addCriterion("waist is not null");
            return (Criteria) this;
        }

        public Criteria andWaistEqualTo(Double value) {
            addCriterion("waist =", value, "waist");
            return (Criteria) this;
        }

        public Criteria andWaistNotEqualTo(Double value) {
            addCriterion("waist <>", value, "waist");
            return (Criteria) this;
        }

        public Criteria andWaistGreaterThan(Double value) {
            addCriterion("waist >", value, "waist");
            return (Criteria) this;
        }

        public Criteria andWaistGreaterThanOrEqualTo(Double value) {
            addCriterion("waist >=", value, "waist");
            return (Criteria) this;
        }

        public Criteria andWaistLessThan(Double value) {
            addCriterion("waist <", value, "waist");
            return (Criteria) this;
        }

        public Criteria andWaistLessThanOrEqualTo(Double value) {
            addCriterion("waist <=", value, "waist");
            return (Criteria) this;
        }

        public Criteria andWaistIn(List<Double> values) {
            addCriterion("waist in", values, "waist");
            return (Criteria) this;
        }

        public Criteria andWaistNotIn(List<Double> values) {
            addCriterion("waist not in", values, "waist");
            return (Criteria) this;
        }

        public Criteria andWaistBetween(Double value1, Double value2) {
            addCriterion("waist between", value1, value2, "waist");
            return (Criteria) this;
        }

        public Criteria andWaistNotBetween(Double value1, Double value2) {
            addCriterion("waist not between", value1, value2, "waist");
            return (Criteria) this;
        }

        public Criteria andHipIsNull() {
            addCriterion("hip is null");
            return (Criteria) this;
        }

        public Criteria andHipIsNotNull() {
            addCriterion("hip is not null");
            return (Criteria) this;
        }

        public Criteria andHipEqualTo(Double value) {
            addCriterion("hip =", value, "hip");
            return (Criteria) this;
        }

        public Criteria andHipNotEqualTo(Double value) {
            addCriterion("hip <>", value, "hip");
            return (Criteria) this;
        }

        public Criteria andHipGreaterThan(Double value) {
            addCriterion("hip >", value, "hip");
            return (Criteria) this;
        }

        public Criteria andHipGreaterThanOrEqualTo(Double value) {
            addCriterion("hip >=", value, "hip");
            return (Criteria) this;
        }

        public Criteria andHipLessThan(Double value) {
            addCriterion("hip <", value, "hip");
            return (Criteria) this;
        }

        public Criteria andHipLessThanOrEqualTo(Double value) {
            addCriterion("hip <=", value, "hip");
            return (Criteria) this;
        }

        public Criteria andHipIn(List<Double> values) {
            addCriterion("hip in", values, "hip");
            return (Criteria) this;
        }

        public Criteria andHipNotIn(List<Double> values) {
            addCriterion("hip not in", values, "hip");
            return (Criteria) this;
        }

        public Criteria andHipBetween(Double value1, Double value2) {
            addCriterion("hip between", value1, value2, "hip");
            return (Criteria) this;
        }

        public Criteria andHipNotBetween(Double value1, Double value2) {
            addCriterion("hip not between", value1, value2, "hip");
            return (Criteria) this;
        }

        public Criteria andCalfIsNull() {
            addCriterion("calf is null");
            return (Criteria) this;
        }

        public Criteria andCalfIsNotNull() {
            addCriterion("calf is not null");
            return (Criteria) this;
        }

        public Criteria andCalfEqualTo(Double value) {
            addCriterion("calf =", value, "calf");
            return (Criteria) this;
        }

        public Criteria andCalfNotEqualTo(Double value) {
            addCriterion("calf <>", value, "calf");
            return (Criteria) this;
        }

        public Criteria andCalfGreaterThan(Double value) {
            addCriterion("calf >", value, "calf");
            return (Criteria) this;
        }

        public Criteria andCalfGreaterThanOrEqualTo(Double value) {
            addCriterion("calf >=", value, "calf");
            return (Criteria) this;
        }

        public Criteria andCalfLessThan(Double value) {
            addCriterion("calf <", value, "calf");
            return (Criteria) this;
        }

        public Criteria andCalfLessThanOrEqualTo(Double value) {
            addCriterion("calf <=", value, "calf");
            return (Criteria) this;
        }

        public Criteria andCalfIn(List<Double> values) {
            addCriterion("calf in", values, "calf");
            return (Criteria) this;
        }

        public Criteria andCalfNotIn(List<Double> values) {
            addCriterion("calf not in", values, "calf");
            return (Criteria) this;
        }

        public Criteria andCalfBetween(Double value1, Double value2) {
            addCriterion("calf between", value1, value2, "calf");
            return (Criteria) this;
        }

        public Criteria andCalfNotBetween(Double value1, Double value2) {
            addCriterion("calf not between", value1, value2, "calf");
            return (Criteria) this;
        }

        public Criteria andThignIsNull() {
            addCriterion("thign is null");
            return (Criteria) this;
        }

        public Criteria andThignIsNotNull() {
            addCriterion("thign is not null");
            return (Criteria) this;
        }

        public Criteria andThignEqualTo(Double value) {
            addCriterion("thign =", value, "thign");
            return (Criteria) this;
        }

        public Criteria andThignNotEqualTo(Double value) {
            addCriterion("thign <>", value, "thign");
            return (Criteria) this;
        }

        public Criteria andThignGreaterThan(Double value) {
            addCriterion("thign >", value, "thign");
            return (Criteria) this;
        }

        public Criteria andThignGreaterThanOrEqualTo(Double value) {
            addCriterion("thign >=", value, "thign");
            return (Criteria) this;
        }

        public Criteria andThignLessThan(Double value) {
            addCriterion("thign <", value, "thign");
            return (Criteria) this;
        }

        public Criteria andThignLessThanOrEqualTo(Double value) {
            addCriterion("thign <=", value, "thign");
            return (Criteria) this;
        }

        public Criteria andThignIn(List<Double> values) {
            addCriterion("thign in", values, "thign");
            return (Criteria) this;
        }

        public Criteria andThignNotIn(List<Double> values) {
            addCriterion("thign not in", values, "thign");
            return (Criteria) this;
        }

        public Criteria andThignBetween(Double value1, Double value2) {
            addCriterion("thign between", value1, value2, "thign");
            return (Criteria) this;
        }

        public Criteria andThignNotBetween(Double value1, Double value2) {
            addCriterion("thign not between", value1, value2, "thign");
            return (Criteria) this;
        }

        public Criteria andForearmIsNull() {
            addCriterion("forearm is null");
            return (Criteria) this;
        }

        public Criteria andForearmIsNotNull() {
            addCriterion("forearm is not null");
            return (Criteria) this;
        }

        public Criteria andForearmEqualTo(Double value) {
            addCriterion("forearm =", value, "forearm");
            return (Criteria) this;
        }

        public Criteria andForearmNotEqualTo(Double value) {
            addCriterion("forearm <>", value, "forearm");
            return (Criteria) this;
        }

        public Criteria andForearmGreaterThan(Double value) {
            addCriterion("forearm >", value, "forearm");
            return (Criteria) this;
        }

        public Criteria andForearmGreaterThanOrEqualTo(Double value) {
            addCriterion("forearm >=", value, "forearm");
            return (Criteria) this;
        }

        public Criteria andForearmLessThan(Double value) {
            addCriterion("forearm <", value, "forearm");
            return (Criteria) this;
        }

        public Criteria andForearmLessThanOrEqualTo(Double value) {
            addCriterion("forearm <=", value, "forearm");
            return (Criteria) this;
        }

        public Criteria andForearmIn(List<Double> values) {
            addCriterion("forearm in", values, "forearm");
            return (Criteria) this;
        }

        public Criteria andForearmNotIn(List<Double> values) {
            addCriterion("forearm not in", values, "forearm");
            return (Criteria) this;
        }

        public Criteria andForearmBetween(Double value1, Double value2) {
            addCriterion("forearm between", value1, value2, "forearm");
            return (Criteria) this;
        }

        public Criteria andForearmNotBetween(Double value1, Double value2) {
            addCriterion("forearm not between", value1, value2, "forearm");
            return (Criteria) this;
        }

        public Criteria andMuscleoxygenIsNull() {
            addCriterion("muscleOxygen is null");
            return (Criteria) this;
        }

        public Criteria andMuscleoxygenIsNotNull() {
            addCriterion("muscleOxygen is not null");
            return (Criteria) this;
        }

        public Criteria andMuscleoxygenEqualTo(Double value) {
            addCriterion("muscleOxygen =", value, "muscleoxygen");
            return (Criteria) this;
        }

        public Criteria andMuscleoxygenNotEqualTo(Double value) {
            addCriterion("muscleOxygen <>", value, "muscleoxygen");
            return (Criteria) this;
        }

        public Criteria andMuscleoxygenGreaterThan(Double value) {
            addCriterion("muscleOxygen >", value, "muscleoxygen");
            return (Criteria) this;
        }

        public Criteria andMuscleoxygenGreaterThanOrEqualTo(Double value) {
            addCriterion("muscleOxygen >=", value, "muscleoxygen");
            return (Criteria) this;
        }

        public Criteria andMuscleoxygenLessThan(Double value) {
            addCriterion("muscleOxygen <", value, "muscleoxygen");
            return (Criteria) this;
        }

        public Criteria andMuscleoxygenLessThanOrEqualTo(Double value) {
            addCriterion("muscleOxygen <=", value, "muscleoxygen");
            return (Criteria) this;
        }

        public Criteria andMuscleoxygenIn(List<Double> values) {
            addCriterion("muscleOxygen in", values, "muscleoxygen");
            return (Criteria) this;
        }

        public Criteria andMuscleoxygenNotIn(List<Double> values) {
            addCriterion("muscleOxygen not in", values, "muscleoxygen");
            return (Criteria) this;
        }

        public Criteria andMuscleoxygenBetween(Double value1, Double value2) {
            addCriterion("muscleOxygen between", value1, value2, "muscleoxygen");
            return (Criteria) this;
        }

        public Criteria andMuscleoxygenNotBetween(Double value1, Double value2) {
            addCriterion("muscleOxygen not between", value1, value2, "muscleoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodpressureIsNull() {
            addCriterion("bloodPressure is null");
            return (Criteria) this;
        }

        public Criteria andBloodpressureIsNotNull() {
            addCriterion("bloodPressure is not null");
            return (Criteria) this;
        }

        public Criteria andBloodpressureEqualTo(Double value) {
            addCriterion("bloodPressure =", value, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodpressureNotEqualTo(Double value) {
            addCriterion("bloodPressure <>", value, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodpressureGreaterThan(Double value) {
            addCriterion("bloodPressure >", value, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodpressureGreaterThanOrEqualTo(Double value) {
            addCriterion("bloodPressure >=", value, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodpressureLessThan(Double value) {
            addCriterion("bloodPressure <", value, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodpressureLessThanOrEqualTo(Double value) {
            addCriterion("bloodPressure <=", value, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodpressureIn(List<Double> values) {
            addCriterion("bloodPressure in", values, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodpressureNotIn(List<Double> values) {
            addCriterion("bloodPressure not in", values, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodpressureBetween(Double value1, Double value2) {
            addCriterion("bloodPressure between", value1, value2, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodpressureNotBetween(Double value1, Double value2) {
            addCriterion("bloodPressure not between", value1, value2, "bloodpressure");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenIsNull() {
            addCriterion("bloodOxygen is null");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenIsNotNull() {
            addCriterion("bloodOxygen is not null");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenEqualTo(Double value) {
            addCriterion("bloodOxygen =", value, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenNotEqualTo(Double value) {
            addCriterion("bloodOxygen <>", value, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenGreaterThan(Double value) {
            addCriterion("bloodOxygen >", value, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenGreaterThanOrEqualTo(Double value) {
            addCriterion("bloodOxygen >=", value, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenLessThan(Double value) {
            addCriterion("bloodOxygen <", value, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenLessThanOrEqualTo(Double value) {
            addCriterion("bloodOxygen <=", value, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenIn(List<Double> values) {
            addCriterion("bloodOxygen in", values, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenNotIn(List<Double> values) {
            addCriterion("bloodOxygen not in", values, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenBetween(Double value1, Double value2) {
            addCriterion("bloodOxygen between", value1, value2, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andBloodoxygenNotBetween(Double value1, Double value2) {
            addCriterion("bloodOxygen not between", value1, value2, "bloodoxygen");
            return (Criteria) this;
        }

        public Criteria andHeartoxygenIsNull() {
            addCriterion("heartOxygen is null");
            return (Criteria) this;
        }

        public Criteria andHeartoxygenIsNotNull() {
            addCriterion("heartOxygen is not null");
            return (Criteria) this;
        }

        public Criteria andHeartoxygenEqualTo(Integer value) {
            addCriterion("heartOxygen =", value, "heartoxygen");
            return (Criteria) this;
        }

        public Criteria andHeartoxygenNotEqualTo(Integer value) {
            addCriterion("heartOxygen <>", value, "heartoxygen");
            return (Criteria) this;
        }

        public Criteria andHeartoxygenGreaterThan(Integer value) {
            addCriterion("heartOxygen >", value, "heartoxygen");
            return (Criteria) this;
        }

        public Criteria andHeartoxygenGreaterThanOrEqualTo(Integer value) {
            addCriterion("heartOxygen >=", value, "heartoxygen");
            return (Criteria) this;
        }

        public Criteria andHeartoxygenLessThan(Integer value) {
            addCriterion("heartOxygen <", value, "heartoxygen");
            return (Criteria) this;
        }

        public Criteria andHeartoxygenLessThanOrEqualTo(Integer value) {
            addCriterion("heartOxygen <=", value, "heartoxygen");
            return (Criteria) this;
        }

        public Criteria andHeartoxygenIn(List<Integer> values) {
            addCriterion("heartOxygen in", values, "heartoxygen");
            return (Criteria) this;
        }

        public Criteria andHeartoxygenNotIn(List<Integer> values) {
            addCriterion("heartOxygen not in", values, "heartoxygen");
            return (Criteria) this;
        }

        public Criteria andHeartoxygenBetween(Integer value1, Integer value2) {
            addCriterion("heartOxygen between", value1, value2, "heartoxygen");
            return (Criteria) this;
        }

        public Criteria andHeartoxygenNotBetween(Integer value1, Integer value2) {
            addCriterion("heartOxygen not between", value1, value2, "heartoxygen");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_user_privacy_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_user_privacy_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}