package com.bkit.fatdown.mappers;

import com.bkit.fatdown.entity.TbAdminMenu;
import com.bkit.fatdown.entity.TbAdminMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbAdminMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_menu
     *
     * @mbg.generated
     */
    long countByExample(TbAdminMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_menu
     *
     * @mbg.generated
     */
    int deleteByExample(TbAdminMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_menu
     *
     * @mbg.generated
     */
    int insert(TbAdminMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_menu
     *
     * @mbg.generated
     */
    int insertSelective(TbAdminMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_menu
     *
     * @mbg.generated
     */
    List<TbAdminMenu> selectByExample(TbAdminMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_menu
     *
     * @mbg.generated
     */
    TbAdminMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbAdminMenu record, @Param("example") TbAdminMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbAdminMenu record, @Param("example") TbAdminMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbAdminMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbAdminMenu record);
}