package com.bkit.fatdown.mappers;

import com.bkit.fatdown.entity.TbAdminRole;
import com.bkit.fatdown.entity.TbAdminRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbAdminRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_role
     *
     * @mbg.generated
     */
    long countByExample(TbAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_role
     *
     * @mbg.generated
     */
    int deleteByExample(TbAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_role
     *
     * @mbg.generated
     */
    int insert(TbAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_role
     *
     * @mbg.generated
     */
    int insertSelective(TbAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_role
     *
     * @mbg.generated
     */
    List<TbAdminRole> selectByExample(TbAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_role
     *
     * @mbg.generated
     */
    TbAdminRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbAdminRole record, @Param("example") TbAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbAdminRole record, @Param("example") TbAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbAdminRole record);
}