package com.bkit.fatdown.mappers;

import com.bkit.fatdown.entity.TbAdmin;
import com.bkit.fatdown.entity.TbAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    long countByExample(TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int deleteByExample(TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int insert(TbAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int insertSelective(TbAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    List<TbAdmin> selectByExample(TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    TbAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbAdmin record, @Param("example") TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbAdmin record, @Param("example") TbAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbAdmin record);
}