package com.bkit.fatdown.mappers;

import com.bkit.fatdown.entity.TbCommonQuestionInstance;
import com.bkit.fatdown.entity.TbCommonQuestionInstanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbCommonQuestionInstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question_instance
     *
     * @mbg.generated
     */
    long countByExample(TbCommonQuestionInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question_instance
     *
     * @mbg.generated
     */
    int deleteByExample(TbCommonQuestionInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question_instance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question_instance
     *
     * @mbg.generated
     */
    int insert(TbCommonQuestionInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question_instance
     *
     * @mbg.generated
     */
    int insertSelective(TbCommonQuestionInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question_instance
     *
     * @mbg.generated
     */
    List<TbCommonQuestionInstance> selectByExampleWithBLOBs(TbCommonQuestionInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question_instance
     *
     * @mbg.generated
     */
    List<TbCommonQuestionInstance> selectByExample(TbCommonQuestionInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question_instance
     *
     * @mbg.generated
     */
    TbCommonQuestionInstance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question_instance
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbCommonQuestionInstance record, @Param("example") TbCommonQuestionInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question_instance
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TbCommonQuestionInstance record, @Param("example") TbCommonQuestionInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question_instance
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbCommonQuestionInstance record, @Param("example") TbCommonQuestionInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question_instance
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbCommonQuestionInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question_instance
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TbCommonQuestionInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question_instance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbCommonQuestionInstance record);
}