package com.bkit.fatdown.mappers;

import com.bkit.fatdown.entity.TbCommonQuestion;
import com.bkit.fatdown.entity.TbCommonQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbCommonQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question
     *
     * @mbg.generated
     */
    long countByExample(TbCommonQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question
     *
     * @mbg.generated
     */
    int deleteByExample(TbCommonQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question
     *
     * @mbg.generated
     */
    int insert(TbCommonQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question
     *
     * @mbg.generated
     */
    int insertSelective(TbCommonQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question
     *
     * @mbg.generated
     */
    List<TbCommonQuestion> selectByExample(TbCommonQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question
     *
     * @mbg.generated
     */
    TbCommonQuestion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbCommonQuestion record, @Param("example") TbCommonQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbCommonQuestion record, @Param("example") TbCommonQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbCommonQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_common_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbCommonQuestion record);
}