package com.bkit.fatdown.mappers;

import com.bkit.fatdown.entity.TbDietElementStandard;
import com.bkit.fatdown.entity.TbDietElementStandardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbDietElementStandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_element_standard
     *
     * @mbg.generated
     */
    long countByExample(TbDietElementStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_element_standard
     *
     * @mbg.generated
     */
    int deleteByExample(TbDietElementStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_element_standard
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_element_standard
     *
     * @mbg.generated
     */
    int insert(TbDietElementStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_element_standard
     *
     * @mbg.generated
     */
    int insertSelective(TbDietElementStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_element_standard
     *
     * @mbg.generated
     */
    List<TbDietElementStandard> selectByExample(TbDietElementStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_element_standard
     *
     * @mbg.generated
     */
    TbDietElementStandard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_element_standard
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbDietElementStandard record, @Param("example") TbDietElementStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_element_standard
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbDietElementStandard record, @Param("example") TbDietElementStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_element_standard
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbDietElementStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_element_standard
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbDietElementStandard record);
}