package com.bkit.fatdown.mappers;

import com.bkit.fatdown.entity.TbDietWeeklyReport;
import com.bkit.fatdown.entity.TbDietWeeklyReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbDietWeeklyReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_weekly_report
     *
     * @mbg.generated
     */
    long countByExample(TbDietWeeklyReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_weekly_report
     *
     * @mbg.generated
     */
    int deleteByExample(TbDietWeeklyReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_weekly_report
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_weekly_report
     *
     * @mbg.generated
     */
    int insert(TbDietWeeklyReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_weekly_report
     *
     * @mbg.generated
     */
    int insertSelective(TbDietWeeklyReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_weekly_report
     *
     * @mbg.generated
     */
    List<TbDietWeeklyReport> selectByExample(TbDietWeeklyReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_weekly_report
     *
     * @mbg.generated
     */
    TbDietWeeklyReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_weekly_report
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbDietWeeklyReport record, @Param("example") TbDietWeeklyReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_weekly_report
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbDietWeeklyReport record, @Param("example") TbDietWeeklyReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_weekly_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbDietWeeklyReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_weekly_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbDietWeeklyReport record);
}