package com.bkit.fatdown.mappers;

import com.bkit.fatdown.entity.TbDietPicture;
import com.bkit.fatdown.entity.TbDietPictureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbDietPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_picture
     *
     * @mbg.generated
     */
    long countByExample(TbDietPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_picture
     *
     * @mbg.generated
     */
    int deleteByExample(TbDietPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_picture
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_picture
     *
     * @mbg.generated
     */
    int insert(TbDietPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_picture
     *
     * @mbg.generated
     */
    int insertSelective(TbDietPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_picture
     *
     * @mbg.generated
     */
    List<TbDietPicture> selectByExample(TbDietPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_picture
     *
     * @mbg.generated
     */
    TbDietPicture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_picture
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbDietPicture record, @Param("example") TbDietPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_picture
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbDietPicture record, @Param("example") TbDietPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_picture
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbDietPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diet_picture
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbDietPicture record);
}