package com.bkit.fatdown.mappers;

import com.bkit.fatdown.entity.TbFeedbackInfo;
import com.bkit.fatdown.entity.TbFeedbackInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbFeedbackInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feedback_info
     *
     * @mbg.generated
     */
    long countByExample(TbFeedbackInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feedback_info
     *
     * @mbg.generated
     */
    int deleteByExample(TbFeedbackInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feedback_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feedback_info
     *
     * @mbg.generated
     */
    int insert(TbFeedbackInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feedback_info
     *
     * @mbg.generated
     */
    int insertSelective(TbFeedbackInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feedback_info
     *
     * @mbg.generated
     */
    List<TbFeedbackInfo> selectByExampleWithBLOBs(TbFeedbackInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feedback_info
     *
     * @mbg.generated
     */
    List<TbFeedbackInfo> selectByExample(TbFeedbackInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feedback_info
     *
     * @mbg.generated
     */
    TbFeedbackInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feedback_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbFeedbackInfo record, @Param("example") TbFeedbackInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feedback_info
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TbFeedbackInfo record, @Param("example") TbFeedbackInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feedback_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbFeedbackInfo record, @Param("example") TbFeedbackInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feedback_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbFeedbackInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feedback_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TbFeedbackInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feedback_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbFeedbackInfo record);
}