package com.bkit.fatdown.mappers;

import com.bkit.fatdown.entity.TbFoodRecommendRecord;
import com.bkit.fatdown.entity.TbFoodRecommendRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbFoodRecommendRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_recommend_record
     *
     * @mbg.generated
     */
    long countByExample(TbFoodRecommendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_recommend_record
     *
     * @mbg.generated
     */
    int deleteByExample(TbFoodRecommendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_recommend_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_recommend_record
     *
     * @mbg.generated
     */
    int insert(TbFoodRecommendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_recommend_record
     *
     * @mbg.generated
     */
    int insertSelective(TbFoodRecommendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_recommend_record
     *
     * @mbg.generated
     */
    List<TbFoodRecommendRecord> selectByExample(TbFoodRecommendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_recommend_record
     *
     * @mbg.generated
     */
    TbFoodRecommendRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_recommend_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbFoodRecommendRecord record, @Param("example") TbFoodRecommendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_recommend_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbFoodRecommendRecord record, @Param("example") TbFoodRecommendRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_recommend_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbFoodRecommendRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_recommend_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbFoodRecommendRecord record);
}