package com.bkit.fatdown.mappers;

import com.bkit.fatdown.entity.TbFoodElementRelation;
import com.bkit.fatdown.entity.TbFoodElementRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbFoodElementRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_element_relation
     *
     * @mbg.generated
     */
    long countByExample(TbFoodElementRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_element_relation
     *
     * @mbg.generated
     */
    int deleteByExample(TbFoodElementRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_element_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_element_relation
     *
     * @mbg.generated
     */
    int insert(TbFoodElementRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_element_relation
     *
     * @mbg.generated
     */
    int insertSelective(TbFoodElementRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_element_relation
     *
     * @mbg.generated
     */
    List<TbFoodElementRelation> selectByExample(TbFoodElementRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_element_relation
     *
     * @mbg.generated
     */
    TbFoodElementRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_element_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbFoodElementRelation record, @Param("example") TbFoodElementRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_element_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbFoodElementRelation record, @Param("example") TbFoodElementRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_element_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbFoodElementRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_food_element_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbFoodElementRelation record);
}