package com.bkit.fatdown.mappers;

import com.bkit.fatdown.entity.TbPaperQuestionRelation;
import com.bkit.fatdown.entity.TbPaperQuestionRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbPaperQuestionRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_paper_question_relation
     *
     * @mbg.generated
     */
    long countByExample(TbPaperQuestionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_paper_question_relation
     *
     * @mbg.generated
     */
    int deleteByExample(TbPaperQuestionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_paper_question_relation
     *
     * @mbg.generated
     */
    int insert(TbPaperQuestionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_paper_question_relation
     *
     * @mbg.generated
     */
    int insertSelective(TbPaperQuestionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_paper_question_relation
     *
     * @mbg.generated
     */
    List<TbPaperQuestionRelation> selectByExample(TbPaperQuestionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_paper_question_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbPaperQuestionRelation record, @Param("example") TbPaperQuestionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_paper_question_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbPaperQuestionRelation record, @Param("example") TbPaperQuestionRelationExample example);
}