package com.bkit.fatdown.mappers;

import com.bkit.fatdown.entity.TbTaskRecord;
import com.bkit.fatdown.entity.TbTaskRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTaskRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_record
     *
     * @mbg.generated
     */
    long countByExample(TbTaskRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_record
     *
     * @mbg.generated
     */
    int deleteByExample(TbTaskRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_record
     *
     * @mbg.generated
     */
    int insert(TbTaskRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_record
     *
     * @mbg.generated
     */
    int insertSelective(TbTaskRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_record
     *
     * @mbg.generated
     */
    List<TbTaskRecord> selectByExample(TbTaskRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_record
     *
     * @mbg.generated
     */
    TbTaskRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbTaskRecord record, @Param("example") TbTaskRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbTaskRecord record, @Param("example") TbTaskRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbTaskRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_task_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbTaskRecord record);
}