package com.bkit.fatdown.mappers;

import com.bkit.fatdown.entity.TbUserBasicInfo;
import com.bkit.fatdown.entity.TbUserBasicInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbUserBasicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_basic_info
     *
     * @mbg.generated
     */
    long countByExample(TbUserBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_basic_info
     *
     * @mbg.generated
     */
    int deleteByExample(TbUserBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_basic_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_basic_info
     *
     * @mbg.generated
     */
    int insert(TbUserBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_basic_info
     *
     * @mbg.generated
     */
    int insertSelective(TbUserBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_basic_info
     *
     * @mbg.generated
     */
    List<TbUserBasicInfo> selectByExample(TbUserBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_basic_info
     *
     * @mbg.generated
     */
    TbUserBasicInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_basic_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbUserBasicInfo record, @Param("example") TbUserBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_basic_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbUserBasicInfo record, @Param("example") TbUserBasicInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_basic_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbUserBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_basic_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbUserBasicInfo record);
}